DokanNet.Tests/DirectoryInfoTest.cs
DokanNet.Tests/DokanOperationsFixture.cs
DokanNet.Tests/DriveInfoTest.cs
DokanNet.Tests/FileInfoTest.cs
DokanNet/DokanOperationProxy.cs
sample/DokanNetMirror/DokanNetMirror.csproj
sample/DokanNetMirror/Mirror.cs

DokanNet
`DokanOperationsProxy` now returns `DokanResult.ExecptionInService` except for rethrowing the .NET Exception to the Dokan driver in all build targets
Activation of tracing switched to define TRACE instead of DEBUG
Minor fixes to glitches in tracing and minor reformatting
Sample\\Mirror
Minor fixes to glitches in Mirror sample
Added tracing to Mirror sample
DokanNet.Tests:
Fixed tests for directory and subdirectory creation
Improved handling of Exceptions thrown in tests

Avoid throwing .NET Exceptions back to Dokan driver

---

DokanNet.Tests/DirectoryInfoTest.cs
DokanNet.Tests/DokanOperationsFixture.cs
DokanNet.Tests/DriveInfoTest.cs
DokanNet.Tests/FileInfoTest.cs
DokanNet.Tests/Properties/AssemblyInfo.cs
DokanNet/Properties/AssemblyInfo.cs

- Unmarked tests `GetDriveFormat_CallsApiCorrectly()` and `GetVolumeLabel_CallsApiCorrectly()` because they have consistently succeeded since dokany 0.8.0 pre-release.
- Fixed test `CopyTo_WhereSourceIsLargeFile_CallsApiCorrectly()`
- Suppress several CodeAnalysis warnings for test method naming
This PR closes https://github.com/dokan-dev/dokan-dotnet/issues/24

Fix DokanNet.Tests [TestCategory.Manual]

---

DokanNet.Tests/DokanNet.Tests.csproj
DokanNet.Tests/FormatProviderTests.cs
DokanNet/DokanFileInfo.cs
DokanNet/DokanNet.csproj
DokanNet/DokanOperationProxy.cs
DokanNet/NullFormatProvider.cs
DokanNet/packages.config
sample/DokanNetMirror/DokanNetMirror.csproj
sample/DokanNetMirror/Mirror.cs

Created format provider, to avoid re-writing the same code over and over to format strings and having one single reliable place to control this aspects.
P.s. this commit add a reference to third party nuget package, that bridge some string interpolation features to .net4 that are available only in 4.6

Using a format provider

---

DokanNet/Logging/DebugViewLogger.cs

If args is null or empty, the message should not be formatted.

Don't format string already formatted.

---

DokanNet/DokanOperationProxy.cs

I have test the changed implementation by run just the changed lines in a separat program.
I iterate from `0` to `0xffff ffff` to test if it was any improvement and to verify that I didn't change functionality.
With the old implementation, the loop took two hour just to go through the first `0x0521 F660` iterations.
For the new implementation, it took **7 s** to test every values from `0` to `0xffffffff`.
That's a pretty big performance improvement.

Improved performance for ZwCreateFileProxy

---

.gitignore
DokanNet/Dokan.cs
DokanNet/DokanFileInfo.cs
DokanNet/DokanOperationProxy.cs
DokanNet/DokanResult.cs
DokanNet/FileAccess.cs
DokanNet/FileInformation.cs
DokanNet/IDokanOperations.cs
DokanNet/Logging/DebugViewLogger.cs
DokanNet/Logging/ILogger.cs
DokanNet/NtStatus.cs
DokanNet/documentations/Doxyfile

Add missing flags to FileAccess and improve documentation.
I have deprecated FileAccess.Reserved and replaced it with FileAccess.AccessSystemSecurity
Related to #117

Add missing flags to FileAccess and improve documentation.

---

DokanNet.Tests/DokanOperationsFixture.cs
DokanNet.Tests/DriveInfoTests.cs
DokanNet.Tests/FileAccessUtils.cs
DokanNet.Tests/Mounter.cs
DokanNet/DokanOperationProxy.cs
DokanNet/Native/NativeMethods.cs
appveyor.yml

I updated the native call to `DokanMapKernelToUserCreateFileFlags` according to the changes in https://github.com/dokan-dev/dokany/commit/0da77870161c101d3133fd76938951c200f12868

Adapt to API changes for dokany 1.1.0

---

DokanNet/DokanOperationProxy.cs

DokanFileInfo.Context allocates a GCHandle if it's set to anything
that isn't null. However, that GCHandle is only ever freed if it
is set to null thereafter. This patch ensures that the GCHandle
is proprly freed before the DokanFileInfo goes out of scope,
without calling anything on the object the Context points to.

Issue #177: DokanFileInfo.Context leaks GCHandle if not set null.

---

DokanNet/Dokan.cs
DokanNet/DokanException.cs
DokanNet/DokanStatus.cs

Currently, the result of DokanMain in case of error is accessible as the HResult of DokanMessage. The meaning of the different possible integer values, however, are not exposed towards the user and only privately listed in the Dokan class as constants.
I would propose to include a public enum DokanStatus in the project that clearly communicates different error states to the user. In addition to the HResult, this strongly typed status value is accessible via the ErrorStatus property in DokanException to allow straightforward error handling in user code.

Expose strongly typed error status in DokanException

---

DokanNet/DokanResult.cs
DokanNet/IDokanOperations.cs
sample/DokanNetMirror/Mirror.cs

NotADirectory was part of NtStatus but not of DokanResult. As it is a valid return value for CreateFile in some cases, it should be included in DokanResult so that consistent uses of enums can be achieved in CreateFile.
I also replaced all usages of NtStatus in the DokanNetMirror implementation with DokanResult for consistency.

Added NotADirectory enum value to DokanResult.

---

sample/DokanNetMirror/Mirror.cs

fix: while invoking DIR from command prompt Mirror.CreateFile() was throwing an exception

CreateFile should not check if a path is a file or a directory if the path do not exist

---

DokanNet/Dokan.cs
DokanNet/DokanFileInfo.cs
DokanNet/Native/NativeMethods.cs

Added methods to support dokany v1.3.0.1000's new kernel notifications, per #234.
The public dokannet interface for these requires passing the DokanFileInfo that the DokanOperations methods receive, so that the filenames passed can be in the same form that the DokanOperations methods receive (where the root of the filesystem implemented is `@"\"`). This contrasts with the kernel notification functions, which require the full path (including the mountpoint) being part of the filename they're called with.  This means that we need to dig the mountpoint out of the DFI, since implementation classes don't usually track their own mountpoint. We do this with a new internal accessor DokanFileInfo.NativeDokanOptions that exposes the private member DokanFileInfo._dokan_context (which is an IntPtr …

Add methods to support Dokany 1.3.0.1000's new kernel notifications

---

DokanNet/Dokan.cs
DokanNet/DokanFileInfo.cs

This is a continuation of #236, to fix a misunderstanding (and undo the dokan-dotnetification of the API) of the Dokan file-change notification functions.  These functions can be called at any time, and are intended to be called from outside of the IDokanOperations implementation to notify the kernel when a file has changed outside of the standard filesystem flow.  DokanFileInfo isn't going to be available at that time, so we have no means of obtaining the MountPoint of the filesystem -- and indeed, it doesn't look like there's any limitation of the API to only files in the filesystem implementation process's mounted filesystem(s) anyway.

Removing DokanFileInfo from new calls, as it's not needed

---

DokanNet.Tests/DokanOperationsFixture.cs
DokanNet.Tests/LogExtensions.cs
DokanNet/DokanFileInfo.cs
DokanNet/IDokanFileInfo.cs
DokanNet/IDokanOperations.cs
DokanNet/IDokanOperationsUnsafe.cs
DokanNet/MockDokanFileInfo.cs
sample/DokanNetMirror/Mirror.cs
sample/DokanNetMirror/UnsafeMirror.cs
sample/RegistryFS/Program.cs

**THIS IS A BREAKING CHANGE.**
All implementations of `IDokanOperations` will need to change their final
parameters to accept `IDokanFileInfo` instead of bare `DokanFileInfo`.
New class: `MockDokanFileInfo` This is accepted by implementations of
`IDokanOperations` and `IDokanOperationsUnsafe` as their final
parameters.  You can set all of the values of the public
interfaces of `IDokanFileInfo` (which itself was extracted from the
publicly accessible fields of `DokanFileInfo`), and specify the
mock behavior of both `.TryResetTimeout()` and `.GetRequestor()`.
To use this, your mock code needs to behave as though it is
Dokan, calling into your `IDokanOperations` implementation with
various parameters and testing the expected behaviors and return
values.

IDokanFileInfo is now the final parameter for IDokanOperations(Unsafe).

---

DokanNet/DokanOptions.cs
sample/DokanNetMirror/Notify.cs
sample/DokanNetMirror/Program.cs

These changes add a reference-implementation for the file-change notifications API added with Dokan 1.3.0 to the mirror-sample.
Further, I also included a fix to a the missing `EnableNotificationAPI `-flag like I mentioned in https://github.com/dokan-dev/dokan-dotnet/pull/236#issuecomment-538937630

Add reference implementation for DokanNotify* to mirror-sample

---

DokanNet/DokanNet.csproj

As per NuGet's docs on [Packing a license expression or a license file](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-a-license-expression-or-a-license-file), the syntax wasn't quite right.
If you run `dotnet pack` on the project then check `obj/[Debug|Release]/DokanNet.1.3.0.nuspec`, you'll see without these changes there is no `<license` element in the `<metadata>` section, but with this change the license is there.
I opted for using the license expression since it allows customers to see what license it is directly from Visual Studio's Package Manager UI and on nuget.org. When using a file, both just show a link and the customer has to click it to see what the license is. I removed the license file from the package since an expression is used, but if you care …

Fix package license

---

DokanNet/DokanNet.csproj

This PR updates the NuGet package references for .NET Standard 1.3 and adds support for .NET Standard 2.0 to reduce the number of dependencies when targetting .NET Core 2.0 or higher.

Update nuget package references + support for .net standard 2.0

---

DokanNet/DokanOptions.cs

Added values for `DOKAN_OPTION_CASE_SENSITIVE` (as `CaseSensitive`) and `DOKAN_OPTION_ENABLE_UNMOUNT_NETWORK_DRIVE` (as `EnableNetworkUnmount`) to enum `DokanOptions`. Copied over documentation from `dokan\dokan.h`

Add additional options from Dokany v1.4.X

---

DokanNet/BufferPool.cs
DokanNet/DokanOperationProxy.cs
DokanNet/Logging/ConsoleLogger.cs
DokanNet/Logging/DebugViewLogger.cs
DokanNet/Logging/ILogger.cs
DokanNet/Logging/Logger.cs
DokanNet/Logging/NullLogger.cs
DokanNet/Logging/TraceLogger.cs

In a high-performance file system, the calls to `ILogger.Debug` accounts for a significant amount of allocations. Even though the logger may ignore the messages, `object[]` arrays are still allocated for each call that have arguments, and every value type argument is boxed causing further allocations.
For production operation, Debug messages are usually not needed, so to avoid these allocations I am adding a `ILogger.DebugEnabled` property that allows the logger to declare whether it wants debug messages. If not, all the debug logging  (and allocations) is skipped.
It is technically a breaking change to add a method to an existing interface that library users may be implementing. But it only affects anybody that has a custom `ILogger `implementation (the provided ones in DokanNet have …

Add ability to disable calls to ILogger.Debug

---

.gitignore
DokanNet.Tests/DokanNet.Tests.csproj
DokanNet.Tests/Mounter.cs
DokanNet.Tests/OverlappedTests.cs
DokanNet/Dokan.cs
DokanNet/DokanHandle.cs
DokanNet/DokanInstance.cs
DokanNet/DokanNet.csproj
DokanNet/Native/DOKAN_OPERATIONS.cs
DokanNet/Native/DOKAN_OPTIONS.cs
DokanNet/Native/NativeMethods.cs
DokanNet/NativeStructWrapper.cs
sample/DokanNetMirror/DokanNetMirror.csproj
sample/DokanNetMirror/Program.cs
sample/DokanNetMirror/Properties/launchSettings.json
sample/RegistryFS/Program.cs

* Implemented manual marshalling of structures and wrapped them and original managed objects in SafeBuffer derived classes to keep managed data alive while the native structure is in use.
* DOKAN_OPTIONS and DOKAN_OPERATIONS changed to classes instead of structs so that they do not need as much copying around and it also makes the "keep-alive" logic simpler.
* IDisposable DokanInstance with a Dispose method that cleans up native allocations.
* DokanHandle class that implements SafeHandle logic for Dokan handles.
* Dokan.CloseFileSystem() removed and replaced with DokanInstance.Dispose().
* Added launchSettings.json to .gitignore because that file contains settings that each developer mostly want to have their own settings. It is only used when debugging in Visual Studio.
* Had to remove …

Unmanaged struct keep-alive logic for async mount

---

DokanNet/DokanOperationProxy.cs

The call ends up looking like this:
```csharp
logger.Debug("\tContext\t{FileStream, ...}")
```
And the `Debug` interprets it as a format string, and the part of the string between curly braces gets incorrectly interpreted as a placeholder specification.
IMHO, a mature logging library should be used instead like [Microsoft.Extensions.Logging](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions/)
Or at the very least to prevent an issue like this there should be an overload without `params object[] args` which would have been selected instead, and which would take the string as the final message rather than format string.

Fixed a crash in `ReadFileProxy` when debug logging is enabled

---

sample/DokanNetMirror/Mirror.cs

Fixes a bug where certain pieces of software (Libre office/Free office) try to open a filestream with FileMode.CreateNew and FileShare.Read which throws an IO exception.

Fixed Mirror.cs FileStream bug

---

DokanNet/DokanNet.csproj

To fix the missing XML documentation files (issue #275), add a single line to the .csproj file, then the generated nuget package now contains XML documentation.

Add "GenerateDocumentationFile" to project file
