dokan-dev/dokan-dotnet

- DokanNet/IDokanOperations.cs
> Bugfix. See DokanOperationProxy

- DokanNet.Tests/DirectoryInfoTest.cs
- DokanNet.Tests/DokanOperationsFixture.cs
- DokanNet.Tests/DriveInfoTest.cs
- DokanNet.Tests/FileInfoTest.cs
- appveyor.yml
Implemented timing tests for file read and write operations
Excluded TestCategory "Timing" from AppVeyor
Added tests for recursive directory listing and access to non-root directories
> Additional tests

- DokanNet.Tests/DirectoryInfoTest.cs
- DokanNet.Tests/DokanOperationsFixture.cs
- DokanNet.Tests/FileInfoTest.cs
- DokanNet.Tests/Properties/AssemblyInfo.cs
Additional tests for FileInfo read/write operations using a context object passed via the DokanInfo.Context property
Adjusted version number of test assembly to main assembly
>  Implement tests for the passing of context info via the DokanInfo.Context property

- DokanNet.Tests/DokanOperationsFixture.cs
- DokanNet.Tests/FileInfoTest.cs
during FileInfo read/write operations
> Added tests for flushing, locking, and unlocking of a FileStream

- DokanNet.Tests/DokanNet.Tests.csproj
- DokanNet.Tests/DokanOperationsFixture.cs
- DokanNet.Tests/packages.config
- DokanNet/DokanOperationProxy.cs
- Replace Thread.Wait(...) with Thread.Yield(...) to allow more efficient synchronizationof alternate threads in single core environments.
- Detect pending files count underflow (< 0)
> Improve single core thread handling

- DokanNet/DokanNet.nuspec
https://docs.nuget.org/create/creating-localized-packages
> add resource file to the nuspec

- sample/DokanNetMirror/Mirror.cs
c#6 allow String interpolation wich is way more readable and nameof() so why not using it ? 
for example mount and unmount were a little wrong ...
> Taking advantage of new c#6 features

- DokanNet.Tests/DirectoryInfoTest.cs
- DokanNet.Tests/DokanOperationsFixture.cs
- DokanNet.Tests/FileInfoTests.cs
- DokanNet/DokanOperationProxy.cs
- sample/RegistryFS/Program.cs
> Handling of DateTime.MinValue

- CHANGELOG.md
- DokanNet.sln
Write a comment in CHANGELOG.ms about v1.0.6
Add some missing files to the solution.
> Fix Markedown issues in CHANGELOG.md

- DokanNet/DokanNet.net4.0.csproj
- DokanNet/DokanNet.net4.6.csproj
- sample/DokanNetMirror/DokanNetMirror.csproj
- sample/RegistryFS/RegistryFS.csproj
In the project files it is stuf from .NET 3.5 and OneClick.
I've cleaned up everything I judge to be unnecessary or irrelevant.
> Clean out remnants from .NET 3.5 in the project files

- DokanNet/Dokan.cs
- DokanNet/DokanException.cs
- DokanNet/DokanFileInfo.cs
- DokanNet/DokanOperationProxy.cs
- DokanNet/DokanOptions.cs
- DokanNet/DokanResult.cs
- DokanNet/FileAccess.cs
- DokanNet/FileInformation.cs
- DokanNet/FileSystemFeatures.cs
- DokanNet/IDokanOperations.cs
- DokanNet/Logging/ILogger.cs
- DokanNet/Native/NativeMethods.cs
- DokanNet/Native/WIN32_FIND_STREAM_DATA.cs
- DokanNet/NtStatus.cs
- DokanNet/NullFormatProvider.cs
Add XML comments to everything in NtStatus and some minor fixes
Note that it is some flags in NtStatus that I think have wrong value. Can you please look at them, I have noted them with a TODO comment.
> Add XML comments to everything in NtStatus

- sample/DokanNetMirror/Mirror.cs
found a bug with drive letters case
> Updated mirror.cs

- CHANGELOG.md
- DokanNet/Dokan.cs
> Corrects the use of timeout in mount

- DokanNet.Tests/DokanNet.Tests.csproj
- sample/DokanNetMirror/Mirror.cs
- sample/DokanNetMirror/Win32.cs
This solves https://github.com/dokan-dev/dokan-dotnet/issues/136
> Fix Mirror.cs implementation of SetTime to work on open files.

- DokanNet/Logging/ConsoleLogger.cs
Avoid console logger to switch color and never go back to the original due to multi threading
> Avoid console logger to switch color and never go back

- DokanNet/Logging/ConsoleLogger.cs
This is a faster version, no threads wait for the others to complete, just one thread write the output
> Faster ConsoleLogger

- DokanNet/DokanOptions.cs
Added values for `DOKAN_OPTION_DISABLE_OPLOCKS` (as `DisableOplocks`) and `DOKAN_OPTION_OPTIMIZE_SINGLE_NAME_SEARCH` (as `OptimizeSingleNameSearch`) to the enum `DokanOptions`.  Copied over the documentation, translating as appropriate into Visual Studio Intellisearch processing dialect.
> Add additional options from Dokany v1.3.0.1000

- sample/DokanNetMirror/Mirror.cs
According to https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-writefile
one should append to the file if the offset is set to -1.
> Append to stream when offset is -1 in mirror

- DokanNet/Dokan.cs
As requested in https://github.com/dokan-dev/dokan-dotnet/pull/284/#issuecomment-1043381198 , here the introduction of the ConfigureInstance method, which deduplicates code from Mount and CreateFileSystem.
> Deduplicate code of Mount and CreateFileSystem

- sample/DokanNetMirror/DokanNetMirror.csproj
- sample/DokanNetMirror/Extensions.cs
- sample/DokanNetMirror/Mirror.cs
- sample/DokanNetMirror/NativeMethods.cs
- sample/DokanNetMirror/UnsafeMirror.cs
Little refactor to remove some warnings and tidy up
> Support pagingIo in mirror.net

- DokanNet/DokanInstanceNotifyCompletion.cs
- DokanNet/DokanNet.csproj
- DokanNet/Extensions.cs
- DokanNet/Native/NativeMethods.cs
- sample/DokanNetMirror/DokanNetMirror.csproj
- sample/DokanNetMirror/Program.cs
Requires native DokanRegisterWaitForFileSystemClosed in dokany PR #1171
> WaitForFileSystemClosedAsync implementation
